//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI_POI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formas_pago
    {
        public int id_Forma_pago { get; set; }
        public string nombre { get; set; }
        public int id_FormasPago { get; set; }
        public int facturas_id_Facturas { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
