//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI_POI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYNEGOCIOEntities : DbContext
    {
        public MYNEGOCIOEntities()
            : base("name=MYNEGOCIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<formas_pago> formas_pago { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<tipos_documento> tipos_documento { get; set; }
    }
}
