//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI_POI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_documento
    {
        public int id_TipoDocumento { get; set; }
        public string nombre { get; set; }
        public int clientes_id_cliente { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
